2024-02-20 10:08:42 | INFO | model_worker | Loading the model ['Qwen1.5-14B-Chat'] on worker 815a3142 ...
2024-02-20 10:08:42 | ERROR | stderr | Process model_worker - Qwen1.5-14B-Chat:
2024-02-20 10:08:42 | ERROR | stderr | Traceback (most recent call last):
2024-02-20 10:08:42 | ERROR | stderr |   File "/home/dell/anaconda3/envs/ychatchat/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-02-20 10:08:42 | ERROR | stderr |     self.run()
2024-02-20 10:08:42 | ERROR | stderr |   File "/home/dell/anaconda3/envs/ychatchat/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-02-20 10:08:42 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-02-20 10:08:42 | ERROR | stderr |   File "/home/dell/Music/Langchain-Chatchat/startup.py", line 389, in run_model_worker
2024-02-20 10:08:42 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-02-20 10:08:42 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20 10:08:42 | ERROR | stderr |   File "/home/dell/Music/Langchain-Chatchat/startup.py", line 217, in create_model_worker_app
2024-02-20 10:08:42 | ERROR | stderr |     worker = ModelWorker(
2024-02-20 10:08:42 | ERROR | stderr |              ^^^^^^^^^^^^
2024-02-20 10:08:42 | ERROR | stderr |   File "/home/dell/anaconda3/envs/ychatchat/lib/python3.11/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-02-20 10:08:42 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-20 10:08:42 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-02-20 10:08:42 | ERROR | stderr |   File "/home/dell/anaconda3/envs/ychatchat/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 348, in load_model
2024-02-20 10:08:42 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-02-20 10:08:42 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20 10:08:42 | ERROR | stderr |   File "/home/dell/anaconda3/envs/ychatchat/lib/python3.11/site-packages/fastchat/model/model_adapter.py", line 1685, in load_model
2024-02-20 10:08:42 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2024-02-20 10:08:42 | ERROR | stderr |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20 10:08:42 | ERROR | stderr |   File "/home/dell/anaconda3/envs/ychatchat/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
2024-02-20 10:08:42 | ERROR | stderr |     return model_class.from_pretrained(
2024-02-20 10:08:42 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20 10:08:42 | ERROR | stderr |   File "/home/dell/anaconda3/envs/ychatchat/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3338, in from_pretrained
2024-02-20 10:08:42 | ERROR | stderr |     raise EnvironmentError(
2024-02-20 10:08:42 | ERROR | stderr | OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /usr/local/yang/models/Qwen/Qwen1.5-14B-Chat.
